### ISSUE TITLE
Can not delete the deployement in progess

### ISSUE THREAD

**Issue by papapillon** [Zorin95670/octo#9]
**Describe the bug**
Once we are log to octo as admin user, we are not able to stop deployment in progress.

**To Reproduce**
1. Have a deployments in progress
2. log to octo
3. click on the button stop
4. See error in dev console and octo_spy logs

**Expected behavior**
Change the deployment status to stop. 

**Screenshots**
![image](https://user-images.githubusercontent.com/32190153/132361509-51757cf3-d509-463b-9bb0-429ac61b78b8.png)
![image](https://user-images.githubusercontent.com/32190153/132361581-966f73a2-283b-4a94-9491-98669917bb4b.png)

**Application (please complete the following information):**
- Octo board v2.5.0 
- Octo spy 1.11.0

**Comment by Zorin95670** [comment]
Hi, thank's for your report. I will fix it and notify you on which version the fix will applied :)

**Comment by Zorin95670** [comment]
I try to reproduce the bug, but it seem's to be not broken.

So I have one question:

After cliking on the stop progress button and Yes button on the validation popup, if you refresh the page is the progress still here ?

Or just after the error if you refresh the page, the deployment is still in progress ?

**Comment by Zorin95670** [comment]
To reproduce the bug I need to : 
- create deployment 
- add progress on it
- go on application
- delete progress on database
- click on delete progress button

So, I think, the progress was delete by an another proccess.

Waiting for auto-refresh fonctionnality, I will add an table update on 404 response. That permit to remove progress state without reloading the page.

**Comment by Zorin95670** [comment]
It was fix in octo-board `2.6.1`. I notify you when the corresponding octo version was release :) .

**Comment by Zorin95670** [comment]
Octo version 1.3.0 was release and fix this issue.

**Comment by Malizor** [comment]
This is still happening. Now the "stop progress" button in the board works, but if we reload the board the progress is still there.

The main problem is that the API tells us there is a progress but there is no actual deletable progress.

More test is needed, but I suppose this happens when a deployment is aborted and retried: in this case we have two progress running and it's not possible to delete the past progresses.
We workaround this issue by emptying the progress table manually.

I thing posting a new progress on a specific project should automatically remove any past progress for it (eg. only one progress per project/environment at a time).
Alternatively, the "stop progress" button should actually remove all existing progresses for the given project/environment, not just the last one.

**Comment by Zorin95670** [comment]
Thank for you repli and precision on bug, I reopen the issue.

I will notify you when this bug is fixed and tell you the associated version 😄 !

**Comment by Zorin95670** [comment]
According to your response, the version 1.3.1 of octo is release and fix the problem.
